[2024-12-23T20:01:33.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T20:01:33.759+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_connect.my_task manual__2024-12-23T19:56:11.738536+00:00 [queued]>
[2024-12-23T20:01:33.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_connect.my_task manual__2024-12-23T19:56:11.738536+00:00 [queued]>
[2024-12-23T20:01:33.768+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-12-23T20:01:33.780+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): my_task> on 2024-12-23 19:56:11.738536+00:00
[2024-12-23T20:01:33.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T20:01:33.788+0000] {standard_task_runner.py:63} INFO - Started process 1890 to run task
[2024-12-23T20:01:33.788+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_connect', 'my_task', 'manual__2024-12-23T19:56:11.738536+00:00', '--job-id', '1059', '--raw', '--subdir', 'DAGS_FOLDER/dag_connect.py', '--cfg-path', '/tmp/tmpe8yyjldp']
[2024-12-23T20:01:33.789+0000] {standard_task_runner.py:91} INFO - Job 1059: Subtask my_task
[2024-12-23T20:01:33.830+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_connect.my_task manual__2024-12-23T19:56:11.738536+00:00 [running]> on host 87a1e11545b0
[2024-12-23T20:01:33.929+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_connect' AIRFLOW_CTX_TASK_ID='my_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T19:56:11.738536+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T19:56:11.738536+00:00'
[2024-12-23T20:01:33.930+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T20:01:33.946+0000] {base.py:84} INFO - Using connection ID 'my_postgres' for task execution.
[2024-12-23T20:01:33.946+0000] {logging_mixin.py:188} INFO - Host: jdbc:postgresql://localhost:5436/de_course_db
[2024-12-23T20:01:33.946+0000] {logging_mixin.py:188} INFO - Login: postgres
[2024-12-23T20:01:33.946+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-23T20:01:33.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T20:01:33.955+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_connect, task_id=my_task, run_id=manual__2024-12-23T19:56:11.738536+00:00, execution_date=20241223T195611, start_date=20241223T200133, end_date=20241223T200133
[2024-12-23T20:01:34.002+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-23T20:01:34.014+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T20:01:34.016+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
